import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="max-w-screen-2xl px-3 pb-8 md:pb-12 lg:px-0">
      <div className="mx-auto mt-10 max-w-4xl rounded-lg p-6 text-gray-600 shadow-lg dark:bg-gray-950 dark:text-gray-200">
        <h1 className="mb-4 text-center text-2xl font-bold">Privacy Policy</h1>

        <p className="mb-4 text-right text-sm">
          Last updated: {new Date().toDateString()}
        </p>

        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mb-8">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="mb-4 text-2xl font-bold">
          Interpretation and Definitions
        </h2>

        <h3 className="mb-2 text-xl font-bold">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="mb-2 text-xl font-bold">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="mb-8 list-inside list-disc">
          <li>
            <strong className="">Account:</strong> means a unique account
            created for You to access our Service or parts of our Service.
          </li>
          <li>
            <strong className="">Affiliate:</strong> means an entity that
            controls, is controlled by, or is under common control with a party,
            where &quot;control&quot; means ownership of 50% or more of the shares, equity
            interest, or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong className="">Application:</strong> refers to BIT—Build It
            Better, the software program provided by the Company.
          </li>
          <li>
            <strong className="">Company:</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Build It
            Better Sokoban Wood Village Company, PLT A5 BLOCK 7, Sokoban.
          </li>
          <li>
            <strong className="">Cookies:</strong> are small files that are
            placed on Your computer, mobile device, or any other device by a
            website, containing the details of Your browsing history on that
            website among its many uses.
          </li>
          <li>
            <strong className="">Country:</strong> refers to: Ghana
          </li>
          <li>
            <strong className="">Device:</strong> means any device that can
            access the Service such as a computer, a cellphone, or a digital
            tablet.
          </li>
          <li>
            <strong className="">Personal Data:</strong> is any information that
            relates to an identified or identifiable individual.
          </li>
          <li>
            <strong className="">Service:</strong> refers to the Application or
            the Website or both.
          </li>
          <li>
            <strong className="">Service Provider:</strong> means any natural or
            legal person who processes the data on behalf of the Company. It
            refers to third-party companies or individuals employed by the
            Company to facilitate the Service, to provide the Service on behalf
            of the Company, to perform services related to the Service or to
            assist the Company in analyzing how the Service is used.
          </li>
          <li>
            <strong className="">Usage Data:</strong> refers to data collected
            automatically, either generated by the use of the Service or from
            the Service infrastructure itself (for example, the duration of a
            page visit).
          </li>
          <li>
            <strong className="">Website:</strong> refers to BIT--Build It
            Better, accessible from{" "}
            <Link
              href="https://bims.onrender.com/"
              target="_blank"
              rel="noreferrer"
              className="text-blue-600 underline"
            >
              https://bims.onrender.com/
            </Link>
            .
          </li>
          <li>
            <strong className="">You:</strong> means the individual accessing or
            using the Service, or the company, or other legal entity on behalf
            of which such individual is accessing or using the Service, as
            applicable.
          </li>
        </ul>

        <h2 className="mb-4 text-2xl font-bold">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="mb-2 text-xl font-bold">Types of Data Collected</h3>

        <h6 className="mb-2 text-lg font-bold">Personal Data</h6>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="mb-8 list-inside list-disc">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h6 className="mb-2 text-lg font-bold">Usage Data</h6>
        <p className="mb-8">
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as Your Device&apos;s Internet Protocol
          address (e.g. IP address), browser type, browser version, the pages of
          our Service that You visit, the time and date of Your visit, the time
          spent on those pages, unique device identifiers, and other diagnostic
          data.
        </p>
        <p className="mb-8">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device
          identifiers, and other diagnostic data.
        </p>
        <p className="mb-8">
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </p>

        <h6 className="mb-2 text-lg font-bold">
          Information Collected while Using the Application
        </h6>
        <p className="mb-4">
          While using Our Application, in order to provide features of Our
          Application, We may collect, with Your prior permission:
        </p>
        <ul className="mb-8 list-inside list-disc">
          <li>Information regarding your location</li>
          <li>Information from your Device&apos;s phone book (contacts list)</li>
          <li>
            Pictures and other information from your Device&apos;s camera and photo
            library
          </li>
        </ul>
        <p className="mb-8">
          We use this information to provide features of Our Service, to improve
          and customize Our Service. The information may be uploaded to the
          Company&apos;s servers and/or a Service Provider&apos;s server or it may be
          simply stored on Your device.
        </p>
        <p className="mb-8">
          You can enable or disable access to this information at any time,
          through Your Device settings.
        </p>

        <h6 className="mb-2 text-lg font-bold">
          Tracking Technologies and Cookies
        </h6>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </p>
      </div>
    </main>
  );
}
